### ISSUE TITLE
Use this files

### ISSUE THREAD

**Issue by TheRoom10** [AKASH2907/project_sunroof_india#1]
Hi friends,

We really like your work and would be nice know how initialize this tool. What do we need to put in the system for work correctly? It work automatically or step by stp.

Thanks you!

**Comment by AKASH2907** [comment]
I have added one file, the last commit of .py file that automatically generates the final version, but, I have specifically worked on **Indian Google Satellite Maps**. 

It requires input as a cropped out rooftop image as shown in testcases. Rest is automatic.
