### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by BashCache** [AKASH2907/project_sunroof_india#4]
Hi,
Could you please let us know how the dataset was generated. Did you manually annotate each of the rooftops from Google Satellite Image

**Comment by AKASH2907** [comment]
I manually cropped out the roof for a given geo-location. This is just a small overview of conventional computer vision techniques on diverse ranges of rooftops I encountered. 

For me, the input was cropped out rooftops. Cropping it out and ground truth annotations were someone else's work.
